Update to latest launchpadlib API
The API has changed recently:

http://www.mail-archive.com/launchpad-users@lists.launchpad.net/msg01653.html

Update the lp credential handling to use the new API.

Fixes this error:

bzr: ERROR: exceptions.TypeError: __init__() takes at least 4 arguments (3 given)

Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/bzrlib/commands.py", line 926, in excep
tion_to_return_code
    return the_callable(*args, **kwargs)
  File "/usr/lib/python2.6/dist-packages/bzrlib/commands.py", line 1126, in run_bzr
    ret = run(*run_argv)
  File "/usr/lib/python2.6/dist-packages/bzrlib/commands.py", line 691, in run_argv_aliases
    return self.run(**all_cmd_args)
  File "/usr/lib/python2.6/dist-packages/bzrlib/commands.py", line 713, in run
    return self._operation.run_simple(*args, **kwargs)
  File "/usr/lib/python2.6/dist-packages/bzrlib/cleanup.py", line 135, in run_simple
    self.cleanups, self.func, *args, **kwargs)
  File "/usr/lib/python2.6/dist-packages/bzrlib/cleanup.py", line 165, in _do_with_cleanups
    result = func(*args, **kwargs)
  File "/home/kvalo/.bazaar/plugins/builder/cmds.py", line 543, in run
    if not watch(owner, archive, package_name, base_branch.deb_version):
  File "/home/kvalo/.bazaar/plugins/builder/ppa.py", line 64, in watch
    launchpad = get_lp()
  File "/home/kvalo/.bazaar/plugins/builder/ppa.py", line 42, in get_lp
    launchpad = Launchpad(credentials, EDGE_SERVICE_ROOT)
TypeError: __init__() takes at least 4 arguments (3 given)